accumulate_grad_batches: 8
num_workers: 12

#views: ['C10095_rgb']
#target_label: 'action'
clip_size: None

learning_rate: 0.01
learning_rate_scheduler: 'step' # alternatives: step, onecycle, cosine_annealing
scheduler_step: 100
scheduler_gamma: 0.5

optimizer: 'SGD' # alternatives: SGD

weight_decay: 0.0005
batch_size: 1
test_batch_size: 1
cemse_alpha: 0.22
train_epochs: 400
frame_features: 2048
pose_joint_features: 3
pose_joint_count: 42
model_dim: 256
dropout: 0.22
temporal_layers_count: 3
temporal_state_dim: 768
temporal_model: 'lru' # alternatives: lru, s4d, mamba

# Mamba initialization
#mamba_expand_factor: 2
#mamba_conv_size: 4

# LRU initialization
lru_max_phase:  0.314159265 # pi / 10
lru_min_radius: 0.20
lru_max_radius: 0.99

categories: ['verb', 'noun']
categories_num_classes: [25, 91]
categories_class_weight: './fine-labels-weights.pkl'
modality: 'poses'
